apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piwik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: piwik
    spec:
      containers:
      - name: piwik
        image: quay.io/ukhomeofficedigital/docker-piwik:{{.DRONE_COMMIT_SHA}}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
      #   volumeMounts:
      #   - name: config
      #     mountPath: /piwik/config/
      # volumes:
      # - name: config
      #   secret:
      #     secretName: piwik-config
