apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piwik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: piwik
    spec:
      containers:
      # - name: nginx
      #   image: quay.io/ukhomeofficedigital/nginx-proxy:v1.7.0
      #   imagePullPolicy: Always
      #   env:
      #     - name: PROXY_SERVICE_HOST
      #       value: 'http://127.0.0.1'
      #     - name: PROXY_SERVICE_PORT
      #       value: '80'
      #     - name: NAXSI_USE_DEFAULT_RULES
      #       value: 'FALSE'
      #     - name: ENABLE_UUID_PARAM
      #       value: 'FALSE'
      #     - name: CLIENT_MAX_BODY_SIZE
      #       value: '10'
      #   ports:
      #    - name: http
      #      containerPort: 8080
      #   resources:
      #    limits:
      #     cpu: 100m
      #     memory: 400M
      - name: piwik
        image: quay.io/ukhomeofficedigital/docker-piwik:{{.DRONE_COMMIT_SHA}}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
        env:
          - name: PIWIK_MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: username
          - name: PIWIK_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: password
          - name: PIWIK_MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: host
          - name: PIWIK_MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: port
          - name: PIWIK_MYSQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: dbname
          - name: PIWIK_ADMIN
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: username
          - name: PIWIK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: password
        # livenessProbe:
        #   exec:
        #     command:
        #     - /healthcheck.sh
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        #   periodSeconds: 30
        #   failureThreshold: 10
        # readinessProbe:
        #   exec:
        #     command:
        #     - /healthcheck.sh
        #   initialDelaySeconds: 90
        #   timeoutSeconds: 10
        #   periodSeconds: 30
        #   failureThreshold: 10
