apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piwik
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: piwik
    spec:
      containers:
      - name: piwik
        image: quay.io/ukhomeofficedigital/docker-piwik:{{.DRONE_COMMIT_SHA}}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
        env:
          - name: PIWIK_MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: username
          - name: PIWIK_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: password
          - name: PIWIK_MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: host
          - name: PIWIK_MYSQL_PORT
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: port
          - name: PIWIK_MYSQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: dbname
          - name: PIWIK_ADMIN
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: username
          - name: PIWIK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: admin-user
                key: password
